# Welcome to Jekyll!
#

# Site settings
title: SUKUNG
description: |
  An innovative research  
  platform for modern control  
  crafted by [Huaqiao University](http://eee.hqu.edu.cn/)
owner: yezhuyun
first_published: 2017 # if migrating another site, the year of your first publish
email: yezhuyun2004@sina.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sukung.cn" # the base hostname & protocol for your site
social:
  twitter: 
  github: 
  linkedin-square: 
  facebook-official: 
  google-plus-square: 
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
